server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev

sftp:
  host: srvsftp1.adds.rbkmoney.com
  port: 22
  connectTimeout: 10000
  username: test
  privateKeyPath: keys/sftp.key
  privateKeyPassphrase: test
  parentPath: /home/registry

scheduling:
  fixed:
    rate: 900000
  enabled: true

service:
  invoicing:
    url: http://hellgate:8022/v1/processing/invoicing
    networkTimeout: 5000
  payoutmgmt:
    url: http://payout-manager:8022/payout/management
    networkTimeout: 5000
